version: '3.1'
services:
  redmine:
    image: 'sha256:48d4ebe34acdfcea3bd606d20cfb92b2c4aaba141d054b05fc760b5ec18efc7d'
    ports:
      - '8080:3000'
    volumes:
      - './upload:/usr/src/redmine/files'
    environment:
      REDMINE_DB_MYSQL: mariadb
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey
      REDMINE_PLUGINS_MIGRATE : "true"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
  phpmyadmin:
    image: phpmyadmin
    ports:
      - '8081:80'
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mariadb